services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3rrific\AwsCloudfront\:
    resource: '../Classes/*'

  T3rrific\AwsCloudfront\Ajax\AjaxController:
    public: true;

  T3rrific\AwsCloudfront\Utility\AwsExceptionHandler:
    public: true;

  T3rrific\AwsCloudfront\Provider\ButtonBarProvider:
    tags:
      - name: event.listener
        identifier: 'aws_cloudfront/button-bar-provider'
